app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
 // Welke URL naar welke classe en functie door verwijst)
get('home/index', 'PagesController@index');
get('search/form', 'PagesController@zoeken');
get('detail/{id}', 'PagesController@detail');
get('home/login', 'PagesController@detail');
get('unset', 'PagesController@unsetage');

post('search/query', 'PagesController@search');
post('search/age', 'PagesController@age');
get('popup1', 'PagesController@popup1');
post('popup', 'PagesController@popup');
get('search/category/{id}', 'PagesController@category');

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);


    resource('admin', 'AdminController');

Route::get('home', 'PagesController@index');
Route::post('detail/{id}', array('before'=>'csrf', function($id)
{
    $input = array(
        'comment' => Input::get('comment'),
        'rating'  => Input::get('rating')
    );
    // instantiate Rating model
    $review = new App\Reviews;
    // Validate that the user's input corresponds to the rules specified in the review model
    $validator = Validator::make( $input, $review->getCreateRules());
    // If input passes validation - store the review in DB, otherwise return to product page with error message
    if ($validator->passes()) {
        $review->storeReviewForApp($id, $input['comment'], $input['rating']);
        return Redirect::to('detail/'.$id.'#reviews-anchor')->with('review_posted',true);
    }

    return Redirect::to('detail/'.$id.'#reviews-anchor')->withErrors($validator)->withInput();
}));

app/Reviews.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model as Eloquent;

class Reviews extends Eloquent {
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function applications()
    {
        return $this->belongsTo('App\Apps');
    }

    public function scopeApproved($query)
    {
        return $query->where('approved', true);
    }

    public function scopeSpam($query)
    {
        return $query->where('spam', true);
    }

    public function scopeNotSpam($query)
    {
        return $query->where('spam', false);
    }

    // this function takes in product ID, comment and the rating and attaches the review to the product by its ID, then the average rating for the product is recalculated
    public function storeReviewForApp($appID, $comment, $rating)
    {
        $app = Apps::find($appID);

        // this will be added when we add user's login functionality
        $this->user_id = \Auth::user()->id;

        $this->comment = $comment;
        $this->rating = $rating;
        $app->reviews()->save($this);

        // recalculate ratings for the specified product
        $app->recalculateRating();
    }

    // Validation rules for the ratings
    public function getCreateRules()
    {
        return array(
            'comment'=>'required|min:10',
            'rating'=>'required|integer|between:1,5'
        );
    }

    // Attribute presenters
    public function getTimeagoAttribute()
    {
        $date = \Carbon\Carbon::createFromTimeStamp(strtotime($this->created_at))->diffForHumans();
        return $date;
    }
}

resources/views/pages/detailpagina.blade.php
{{-- Hier word vertelt dat de volgende in de master.blade.php word ingevuld.) --}}
@extends('master')

@section('scripts')

    <script type="text/javascript" src="/js/expanding.js"></script>
@stop

{{-- welke sectie met wat word ingevuld op de master pagina.) --}}
@section('titel')
    Detail pagina

    {{-- @stop komt na elke het einde van elke sectie.) --}}
@stop


@section('content')
<div class="col-xs-4 col-xs-offset-3 col-md-2 col-md-offset-0">
    <img id="detailpictogram" src="{{$app->pic}}">
</div> 

<div class="col-xs-12 col-md-8">
    
    <section id="detailinfo">
       
    {{$app->name}}
    </br>
        <i>
            @foreach ($app->categories as $category)
              {{ $category->name }} /
            @endforeach 
            <!--Als de minimale en de maximale leeftijd gelijk zijn laat alleen de minimale leeftijd zien-->
             @if ($app->minimal === $app->maximal)
                {{ $app->minimal }} jr. 
             @endif
            <!--Als de minimale- en de maximale leeftijd niet gelijk zijn laat allebei zien.-->
             @if($app->minimal !== $app->maximal)
                {{ $app->minimal }} - {{ $app->maximal }} jr. 
             @endif </br>
        </i>
    
        <span>
            @if (!empty($app->android_price))
                <p>Google Play Store: {{$app->android_price}}</p>
            @endif

            @if (!empty($app->ios_price))
                <p>Apple App Store: {{$app->ios_price}}</p>
            @endif
        </span>
       
        
    
    </section>
</div>  

    <div class="col-xs-12 col-md-2 col-md-offset-0">
    <section class="starrating">
            <p>
                @for ($i=1; $i <= 5 ; $i++)
                <span class="glyphicon glyphicon-star{{ ($i <= $app->rating_cache) ? '' : '-empty'}}"></span>
                @endfor
                {{ number_format($app->rating_cache, 1)}} sterren
            </p>
        @if (Auth::user()->user_type == "2")
            <a href="/admin/{{ $app->id }}/edit">Applicatie bewerken</a>
        @endif
    </section>
    </div>



<div id="myCarousel" class="carousel slide col-xs-12 col-md-8 col-md-offset-2" data-ride="carousel">
  <!-- Indicators
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol> -->

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
     @foreach ($app->images as $index => $image)
          <div class="item @if($index == 0) {{ 'active' }} @endif">
              <img src="{{ $image->img_path }}">
          </div>
      @endforeach
  </div>

  @if ($imgcount > 1)
  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
      @endif
</div>



    <div class="col-xs-12 col-md-8 col-md-offset-2">
     <article class="descriptie">
        {{$app->description}} 
     </article>
    </div>

<div class="col-md-6 col-xs-12 col-md-offset-2">
    <section class="link">  
        @if (!empty($app->android_link))
            <a href="{{$app->android_link}}">Klik hier om hem te bekijken in de Google Play Store.</a><br><br>
        @endif
        

             @if (!empty($app->ios_link))
             <a href="{{$app->ios_link}}">Klik hier om hem te bekijken in de Apple App Store.</a><br><br>
            @endif

            <p>Geüpload op: {{$app->created_at}}</p>
    </section>
</div>  
    <!-- <div class="ratings">
        <p class="pull-right">{{$app->rating_count}} {{ Str::plural('review', $app->rating_count)}}</p>
        <p>
            @for ($i=1; $i <= 5 ; $i++)
                <span class="glyphicon glyphicon-star{{ ($i <= $app->rating_cache) ? '' : '-empty'}}"></span>
            @endfor
            {{ number_format($app->rating_cache, 1)}} stars
        </p>
    </div> -->
    
          
   <div class="container">

        <div class="row" style="margin-top:40px;">
            <div class="col-md-6 col-xs-12 col-md-offset-2">
                <div class="well well-sm">
                    @if (Auth::check())
                    <div class="row">
                        <div class="col-md-12">
                            @if(Session::get('errors'))
                                <div class="alert alert-danger">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    <h5>There were errors while submitting this review:</h5>
                                    @foreach($errors->all(':message') as $message)
                                        {{$message}}
                                    @endforeach
                                </div>
                            @endif
                            @if(Session::has('review_posted'))
                                <div class="alert alert-success">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    <h5>Your review has been posted!</h5>
                                </div>
                            @endif
                            @if(Session::has('review_removed'))
                                <div class="alert alert-success">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    <h5>Your review has been removed!</h5>
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="text-right">
                        <a href="#reviews-anchor" id="open-review-box" class="btn btn-success btn-green">Leave a Review</a>
                    </div>
                    <div class="row" id="post-review-box" style="display:none;">
                        <div class="col-md-12">
                            {!!Form::open()!!}
                            {!!Form::hidden('rating', null, array('id'=>'ratings-hidden'))!!}
                            {!!Form::textarea('comment', null, array('rows'=>'5','id'=>'new-review','class'=>'form-control animated','placeholder'=>'Enter your review here...'))!!}
                            <div class="text-right">
                                <div class="stars starrr" data-rating="{{Input::old('rating',0)}}"></div>
                                <a href="#" class="btn btn-danger btn-sm" id="close-review-box" style="display:none; margin-right:10px;"> <span class="glyphicon glyphicon-remove"></span>Cancel</a>
                                <button class="btn btn-success btn-lg" type="submit">Save</button>
                            </div>
                            {!!Form::close()!!}
                        </div>
                    </div>
                    @endif
                    @foreach($reviews as $review)
                        <hr>
                        <div class="row">
                            <div class="col-md-12">
                                @for ($i=1; $i <= 5 ; $i++)
                                    <span class="glyphicon glyphicon-star{{ ($i <= $review->rating) ? '' : '-empty'}}"></span>
                                @endfor

                                {{ $review->user ? $review->user->name : 'Anonymous'}} <span class="pull-right">{{$review->timeago}}</span>

                                <p>{{{$review->comment}}}</p>
                            </div>
                        </div>
                    @endforeach

                  <!--  <a href="/review/{{$app->id}}">Alle Recensies</a> -->
                </div>

            </div>
        </div>
    </div>

    <br><br>


@stop

resources/views/pages/homepage.blade.php
{{-- Hier word vertelt dat de volgende in de master.blade.php word ingevuld.) --}}
@extends('master')

{{-- @section = welke sectie met wat word ingevuld op de master pagina.) --}}
@section('titel')
    Homepage


    {{-- @stop komt na elke het einde van elke sectie.) --}}
@stop


@section('content')
    <?php $leeftijd = Session::get('leeftijd');?>

    @if (empty($leeftijd))
<div id="blackground">

</div>

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Wat is uw kind's leeftijd?</h4>
      </div>
      <div class="modal-body">

          {{--Leeftijd zoekformulier--}}
            {!!Form::open(array('action'=>'PagesController@popup'))!!}
            {!! Form::selectRange('leeftijd', 0, 12) !!}
           {!!Form::submit('Kies')!!}
          {!!Form::close()!!}

    </div>


    <div class="modal-footer">
      <button type="button" class="btn btn-primary" name="leeftijd" value="alle"><a href="/popup1">Weergeef alle leeftijden</a></button>
    </div>

  </div>
</div>
@endif

 <div class="row">

      @foreach ($categorie as $cat)
     <div class="col-xs-12 col-md-6 col-md-offset-0">
         <h1 class="titel"><a href="/search/category/{{ $cat->id }}"> {{ $cat->name }} </a></h1>
@if ($cat->applications->count() !== 0)
           @foreach ($cat->applications->take(4) as $app)
               <div class="pictogram col-xs-5 col-xs-offset-0 col-md-3 col-md-offset-0">
                   <a href="/detail/{{ $app->id }}"> <img src="{{$app->pic}}">

                       {{ $app->name }} </a> </br>

                   <!--Laat de bijbehorende categorieën zien-->
                   @foreach ($app->categories as $category)

                       {{ $category->name }} /
                       @endforeach
                               <!--Als de minimale en de maximale leeftijd gelijk zijn laat alleen de minimale leeftijd zien-->
                       @if ($app->minimal === $app->maximal)
                           {{ $app->minimal }} jr.
                           @endif
                                   <!--Als de minimale- en de maximale leeftijd niet gelijk zijn laat allebei zien.-->
                           @if($app->minimal !== $app->maximal)
                               {{ $app->minimal }} - {{ $app->maximal }} jr.
                           @endif

               </div>
               @endforeach


@else <p>Er zijn geen apps gevonden in deze categorie</p>

    @endif


      </div>
        @endforeach


    </div>
  <?php

  /*$app = $app->whereId("4")->first();

  // Apple of android
  $Apple = array();
  $Apple['UA'] = $_SERVER['HTTP_USER_AGENT'];
  $Apple['Device'] = false;
  $Apple['Types'] = array('iPhone', 'iPod', 'iPad','Android');
  foreach ($Apple['Types'] as $d => $t) {
      $Apple[$t] = (strpos($Apple['UA'], $t) !== false);
      $Apple['Device'] |= $Apple[$t];
  }
    if($Apple['iPhone']){
        $OS = "Ios";
        echo"yay iphone";
    }
    if
    ($Apple['iPad']){
        $OS = "Ios";
        echo"yay ipad";
    }
     if
     ($Apple['Android']){
      $OS = "Android";
         echo"yay android";
    }


  ;


  // is this an Apple device?
  //echo
  //"<p>Apple device? ", ($Apple['Device'] ? 'true' : 'false'),
  //"</p>n<p>iPhone? ", ($Apple['iPhone'] ? 'true' : 'false'),
  //"</p>n<p>iPod? ", ($Apple['iPod'] ? 'true' : 'false'),
  //"</p>n<p>iPad? ", ($Apple['iPad'] ? 'true' : 'false'),
  //'</p>'; */
  ?>








@stop

resources/views/pages/loginpage.blade.php
{{-- Hier word vertelt dat de volgende in de master.blade.php word ingevuld.) --}}
@extends('master')

{{-- welke sectie met wat word ingevuld op de master pagina.) --}}
@section('titel')
    Login pagina

    {{-- @stop komt na elke het einde van elke sectie.) --}}
@stop


@section('content')
   <h1>Create New User</h1>

@stop

resources/views/pages/zoekpagina.blade.php
{{-- Hier word vertelt dat de volgende in de master.blade.php word ingevuld.) --}}
@extends('master')

{{--  welke sectie met wat word ingevuld op de master pagina.) --}}
@section('titel')
        Zoek pagina

@stop               
{{--  @stop komt na elke het einde van elke sectie.) --}}   

@section('content')
{{--Zoekformulier--}}
{!!Form::open(array('url'=>'/search/query'))!!}
{!!Form::text('zoekopdracht', null, array('placeholder'=>'Zoeken'))!!}<br>
    {!!Form::radio('prijs', 'alle', true)!!}Alle<br>
    {!!Form::radio('prijs', 'gratis')!!}Gratis<br>
    {!!Form::radio('prijs', 'betaald')!!}Betaald<br>
    {!!Form::submit('Zoeken')!!}
    {!!Form::close()!!}<br><br><br>

{{--Leeftijd zoekformulier--}}
{!!Form::open(array('url'=>'/search/age'))!!}    
{!! Form::selectRange('leeftijd', 0, 12) !!}
 {!!Form::submit('Zoeken')!!}
{!!Form::close()!!}<br><br><br>

{{--Categorie zoekformulier--}}
{!!Form::open(array('url'=>'/search/category'))!!}    
{!! Form::select('categorie', $categorie) !!}
 {!!Form::submit('Zoeken')!!}
{!!Form::close()!!}<br><br><br>  

@stop

resources/views/pages/zoekresultaat.blade.php
{{-- Hier word vertelt dat de volgende in de master.blade.php word ingevuld.) --}}
@extends('master')

{{-- welke sectie met wat word ingevuld op de master pagina.) --}}
@section('titel')
    Detail pagina

    {{-- @stop komt na het einde van elke sectie.) --}}
@stop


@section('content')

@if (!isset($rows))


    @elseif (empty($rows)||$rows=="")
        Er zijn geen apps gevonden
        @endif


    @foreach ($zoekresultaten as $app)
        <div class="pictogram col-xs-5 col-xs-offset-0 col-md-2 col-md-offset-0">

            <a href="/detail/{{ $app->id }}"> <img src="{{$app->pic}}">

                 {{ $app->name }}
            </a> </br>


            @foreach ($app->categories as $category)

                 {{ $category->name }} /
                    @endforeach

                @if ($app->minimal === $app->maximal)
                    {{ $app->minimal }} jr. 
                @endif

                @if($app->minimal !== $app->maximal)
                    {{ $app->minimal }} - {{ $app->maximal }} jr. 
                @endif
    </div>
            @endforeach
        
@stop